---
title: "Config - R Notebook"
authors:  Rebecca Ross and Genoveva Gonzalez Mirelis
date: "Last Rendered on `r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_notebook: 
    toc: yes
    toc_depth: 2
    toc_float: yes
    fig_width: 7
    fig_height: 7
always_allow_html: true 
---

A config file for the biotopes 2023 project (based on a combinatio of the Mareano/NiN v3.0 work "videoEnvDataPrep" project, and the biotopes 2022 project)

Sets up paths, funcitons, etc - run first before all other scripts

# Libraries

```{r}
## Paths
library(readxl)
```

# Paths

```{r}

delphi_prosjekt_drive <- "U:" # which letter have you mapped this drive to?

coreDirectory <- file.path(delphi_prosjekt_drive,"Mareano/VIDEOLAB/VIDEO DATA/200m_scale_species_by_sample/Data_Delivery_2023")
dataPath <- file.path(coreDirectory,"inputs")

outPath <- file.path(coreDirectory,"outputs")
codePath <- getwd()

sppdens <- read.csv(file.path(dataPath,"species_densities.csv"))
refer <- read.table(file.path(dataPath,"reference.csv"), sep ="|", header = TRUE)
sample_info <- read.csv(file.path(dataPath,"sample_info.csv"))

taxonary <- read_xlsx("C:/Users/a21448/Havforskningsinstituttet/Video analysis lab - Reference List/Taxonary.xlsx", sheet=1)
```


# Functions

```{r}
#convert geographic coordinates in WGS84 to UTM33N

utmize <- function(x){
  require(rgdal)
  proj4string(x)=CRS("+init=epsg:4326")
  result <- spTransform(x, CRS("+init=epsg:32633")) 
  return(result)
}

#Compute mean abundance of all species present in all samples of a given class in a given classification

classreport <- function(data, classifications, level, class){
  aa <- paste0("level",level)
  id <- classifications %>% 
    filter(get(aa)==class) %>%
    select(SampID) %>%
    pull()
  spp <- data %>% filter(SampID %in% id) %>%
    select(-1) %>%
    select_if(colSums(.)>0)
  return(sort(colMeans(spp), decreasing = TRUE))
}

# give me the class membership of all samples containing a given species

spquery <- function(data, classifications, sp){
  extr <- data %>% 
    filter(data[sp]>0)%>%
    select(1) %>%
    pull()
  return(classifications %>% filter(SampID%in%extr))
}

# give me all the samples in a given class

getsamplesingrp <- function(classifications, level, class){
extract <- classifications %>%
  filter(classifications[paste0("level",level)]==class) %>%
  select(1) %>%
  pull()
return(extract)
}


```


